apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
     app: nginx
     tier: frontend	
spec:
  containers:
  -  name: nginx-test
     image: nginx
  -  name: busybox
     image: busybox
 
