apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: nginx
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        tier: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
  replicas: 3
  selector:
    matchLabels:
      app: myapp